### ISSUE TITLE
posición media punta y extremo intercambiadas

### ISSUE THREAD

**Issue by cressidagp** [carky12/EditorPCFutbol6#1]
win10x64
commit: #caae6fd

Un pequeño bug cosmético. En la pantalla de creación de jugador los extremos están en lugar de los media punta y viceversa.

No obstante desde el juego la posición es correcta.

Saludos!

**Comment by carky12** [comment]
Apuntado para la siguiente versión.

Gracias!

**Comment by carky12** [comment]
Listo, esto también está solucionado.

Gracias por el feedback!
