### ISSUE TITLE
Error al abrir equipo dbc Apertura 98

### ISSUE THREAD

**Issue by cressidagp** [carky12/EditorPCFutbol6#10]
### Descripción

Se han producido errores en la carga del fichero DBC.
Error al convertir a decimal: Valor de la letra no conocido BE.

### Como reproducir

1. Cargar archivo original.
2. Consultar equipo 420 Belgrano.
3. Generar DBC sin marcar casillero nombre.
4. Cerrar.
5. Seleccionar Equipos > Abrir Archivo DBC > EQ979006

Intente lo mismo con el fichero de jugadores libres, sin embargo en este caso funciono.

Con Talleres (cba): valor de la letra no conocido DE.

### Versión PC-Fútbol

PCF6 Apertura 98

### Hash/commit

5c8a42eae008e2ce8eec441fee8ad83629dbaf26

**Comment by carky12** [comment]
Gracias de nuevo por el feedbak. En unas horas lo corregiré.

**Comment by cressidagp** [comment]
No sucede en: 

- PC-Calcio6 
- PC6
- PCF6_EXT1
- PCF6_EXT2

**Comment by carky12** [comment]
El problema es debido a que hay caracteres raros que mis funciones de conversión no reconocen. Como digo son caracteres erróneos cuando redactaron la BBDD del juego. Lo mejor que puedo hacer es externalizar estos errores. A partir de ahora habrá un fichero llamado map.txt en el que se tendrán que poner estas parejas de bytes-caracteres para que el editor las reconozca. Pongo el ejemplo con Belgrano para que veas como quedará a partir de ahora.

![image](https://user-images.githubusercontent.com/57545449/126085815-6f7e9e81-7aae-4af1-9178-e84358faf103.png)

Para saber que carácter corresponde con los bytes que dan error hay que ir con el editor hexadecimal y ver que letra o carácter representa:

![image](https://user-images.githubusercontent.com/57545449/126085848-9792a0cd-3947-42e9-b8b8-563b98c0a4be.png)

Está claro que los que redactaron esto querían poner "Área" pero se equivocaron y quedó ese carácter. Lo que tendremos que hacer es cada vez que el editor nos escupa un mensaje de valor desconocido, averiguaremos que valor es y lo pondremos en el archivo map.txt.

No debería de haber muchos, pero entiendo que en una bbdd tan grande como la de PC Fútbol puede pasar "bastante" por lo que creo que es la mejor solución para no tener que estar tocando el código fuente cada poco tiempo.

**Comment by cressidagp** [comment]
Okey Carky estoy familiarizado con Notepad++, necesitaría alguna otra aplicación para dar solución a esto si me van apareciendo mas errores?

**Comment by carky12** [comment]
Nada, simplemente añadir el caracter adecuado en el fichero map.txt y listo.

**Comment by carky12** [comment]
Por ejemplo, para el Liverpool que comentas en la siguiente incidencia habría que añadir esto al fichero map.txt:

40 : !

![image](https://user-images.githubusercontent.com/57545449/126086499-4dea3110-91c9-4897-bd49-9736aebe6c6e.png)

Intentaré explicar esto en el manual del editor de forma detallada. Pero es la mejor solución para que por lo menos cada usuario pueda realizar cargas de equipos sin tener que tocar el código del editor de cada vez que dé un pete de este tipo.

**Comment by cressidagp** [comment]
A mi me sale diferente si trato de editarlos en notepad++
![Sin título](https://user-images.githubusercontent.com/63816325/126086664-1edc1c2f-7cc9-4508-8147-4bce3ad1d4fe.jpg)

**Comment by cressidagp** [comment]
Revise los 480 equipos del Apetura 98. Los errores de tipeo están solo en la liga nacional. 

Independiente: error al convertir a decimal: valor de letra desconocido C7
Arsenal( liga arg): error al convertir a decimal: valor de letra desconocido 5D
Los Andes: error al convertir a decimal: valor de letra desconocido DE ( este también se repite en Talleres ).
Atlético de Rafaela: error al convertir a decimal: valor de letra desconocido D6

En Newells también saltaba el error BE.

**Comment by cressidagp** [comment]
Lista corregida. Había unos errores porque aveces cuando daba el error yo miraba de fondo el equipo que había probado anteriormente.

**Comment by carky12** [comment]
He probado con todos los equipos de todas las ediciones. Sólo haría falta probar con los equipos que tienen información de bbdd pero de forma programática he probado con todos y metiendo estos valores en el map.txt sería suficiente.

BE : Á
40 : !
C1 : ,
5E : ?
C7 : Á
5D : <
DE : .
D6 : .

Por la noche (hora española) hago la subida de todo lo que he corregido.

Aprovecho para hacerte especial mención, me ayudas mogollón a probar el editor!!

**Comment by cressidagp** [comment]
Me alegra haber podido aportar mi granito de arena. Gracias Carky por compartir este proyecto con la comunidad :D
