### ISSUE TITLE
Error al abrir equipo dbc pc premier.

### ISSUE THREAD

**Issue by cressidagp** [carky12/EditorPCFutbol6#11]
### Descripción

Se han producido errores en la carga del fichero DBC.
Error al convertir a decimal: Valor de la letra no conocido 40.

### Como reproducir

1. Cargar archivo original.
2. Consultar equipo 42 Liverpool.
3. Generar DBC sin marcar casillero nombre.
4. Cerrar.
5. Seleccionar Equipos > Abrir Archivo DBC > EQ970305

### Versión PC-Fútbol

PC-Premier 6

### Hash/commit

5c8a42eae008e2ce8eec441fee8ad83629dbaf26

**Comment by carky12** [comment]
Esto se soluciona con el la incidencia anterior.
