### ISSUE TITLE
Error generación de juveniles al guardar archivo.

### ISSUE THREAD

**Issue by cressidagp** [carky12/EditorPCFutbol6#12]
### Descripción

La conversión de la cadena "" en el tipo integer no es valida.

### Como reproducir

1. Cargar archivo original.
2. Consultar equipo 472 Juveniles.
3. Generar DBC sin marcar casillero nombre.
4. Cerrar.
5. Seleccionar Juveniles > Abrir Archivo DBC > EQ979958
6. Hacer algún cambio..
10. Dar click fuera del casillero de media para que se actualicen los demás datos.
11. Guardar

### Versión PC-Fútbol

- PCF6 Apertura 98
- PC-Calcio 6
- PC6
- PCF6_EXT1
- PCF6_EXT2

### Hash/commit

5c8a42eae008e2ce8eec441fee8ad83629dbaf26

**Comment by cressidagp** [comment]
No sucede en PC-Premier 6.

**Comment by carky12** [comment]
Está corregido, el problema radicaba en que las cadenas correspondientes al palmares del equipo estaban vacías y al intentar convertir a Intenger petaba. Lo que hice fue asignar valores por defecto a esos campos del palmarés (sólo para los equipos juveniles). Lo raro es que no te pasara en PC-PREMIER por que la cadena de palmares del equipo tampoco se usa en los Juveniles Ingleses.

**Comment by cressidagp** [comment]
Lo volví a probar y no lo hace... :D

**Comment by carky12** [comment]
En la versión PREMIER 6.0 no da el error ya que en el archivo del juego el equipo JUVENILES INGLESES está definido como equipo de liga extranjera. Para un equipo de liga extranjera nunca se guarda la información del palmarés (que es la que estaba dando problemas al guardar datos a vacío).

En la versión argentina el equipo JUVENILES ARGENTINOS está definido como liga nacional con lo cual el editor va a intentar guardar la información del palmarés del equipo.

PREMIER:
![image](https://user-images.githubusercontent.com/57545449/126165510-a27025ec-56de-48d1-9f2c-3d01a51158a4.png)

![image](https://user-images.githubusercontent.com/57545449/126165540-4b50207c-44b0-4d27-a7b6-28c21e4bd8ab.png)

ARGENTINA:
![image](https://user-images.githubusercontent.com/57545449/126165671-804e690b-07fd-4073-997e-c6f8d235f13b.png)

![image](https://user-images.githubusercontent.com/57545449/126165701-b14d504a-fe19-403d-80c6-c446c2407ae9.png)

Sea como sea que esté definido el equipo ya no dará problema nunca , por que he optado por inicializar los datos de palmarés.
