### ISSUE TITLE
Selecciones

### ISSUE THREAD

**Issue by cressidagp** [carky12/EditorPCFutbol6#13]
### Descripción

No aparecen los jugadores en los archivos DBC de selección América y Europa.

![Sin título2](https://user-images.githubusercontent.com/63816325/126082680-43b42c4c-7fc9-41b8-b567-360aaa955cc8.jpg)

### Como reproducir

1. Cargar archivo original.
2. Consultar equipos:  459 - Selección Europa y 460 Selección América.
3. Generar DBC sin marcar casillero nombre.
4. Cerrar.
5. Seleccionar Equipo > Abrir Archivo DBC

### Versión PC-Fútbol

- PCF6 Apertura 98
- PC-Calcio 6
- PC-Premier 6
- PC6
- PCF6_EXT1
- PCF6_EXT2

### Hash/commit

5c8a42eae008e2ce8eec441fee8ad83629dbaf26

**Comment by cressidagp** [comment]
Agrego imagen para que sea mas explicativo.

**Comment by carky12** [comment]
Respecto a esto, el EDITOR lee exactamente lo que hay en el fichero del juego, que es eso que ves tú en el pantallazo. 

![image](https://user-images.githubusercontent.com/57545449/126167175-03e82b96-a420-40e0-a3e4-a97f8553d2ca.png)

Supongo que serán datos "inventados" por que los equipos Sel. Europa y América se forman dentro del propio juego.

No le doy mucha importancia, es más, creo que en una edición estos equipos no deberían tocarse.
