### ISSUE TITLE
Las medias suelen irse un punto hacia arriba en algunos casos.

### ISSUE THREAD

**Issue by cressidagp** [carky12/EditorPCFutbol6#14]
### Descripción

Bueno Carky esto es lo último porque creo que me he excedido jajaja.

Veamos ejemplos:

Si buscamos a Dragan STOJKOVIC con el secretario aparecerá con media 83. 
Si buscamos a Michael LAUDRUP con el secretario aparecerá con media 87.

Veamos que pasa si generamos el archivo dbc de estrellas y lo abrimos:

![Sin título](https://user-images.githubusercontent.com/63816325/126082409-4dfad2c7-2575-4e2e-953e-0f51741870f3.jpg)

Como se puede ver, ambos casos tienen media + 1

En la versión anterior ya había aparecido este problema en ocaciones. Siempre haciendo archivos DBC desde cero.

### Como reproducir

1. Cargar archivo original.
2. Consultar equipos:  Estrellas ARGENTINA
3. Generar DBC sin marcar casillero nombre.
4. Cerrar.
5. Seleccionar Equipo > Abrir Archivo DBC

### Versión PC-Fútbol

- PCF6 Apertura 98

### Hash/commit

5c8a42eae008e2ce8eec441fee8ad83629dbaf26

**Comment by cressidagp** [comment]
Con respecto a esto hice una prueba mas. Genere el archivo dbc correspondiente a San Lorenzo y pude ver que casi el 70% de los jugadores tenia media + 1.

**Comment by carky12** [comment]
Hola, ya está solucionado. El problema era que las medias se redondeaban al alza cuando daba justo .5. Por ejemplo en el caso de Laudrup da  91+83+79+97 = 350. Para la media quedaría 350 / 4 = 87.5. 

Ahora este tipo de medias se truncan para que quede como en el juego.

PD: Menuda media de pase tenía este tipo, fue uno de mis jugadores admirados de la infancia!

**Comment by cressidagp** [comment]
Vos sabes que fichar los hermanos Laudrup era mi objetivo prioritario en todas las partidas. Los dos tenían media 87 :P
