### ISSUE TITLE
Intercambiar jugadores: error al convertir a hexadecimal.

### ISSUE THREAD

**Issue by cressidagp** [carky12/EditorPCFutbol6#18]
### Descripción

No se puede enviar jugador de equipo de liga inglesa a un equipo de liga argentina.
Si se puede enviar de liga argentina a liga inglesa.

Error al convertir a hexadecimal: Valor de nacionalidad no conocido x

### Como reproducir

1. Cargar archivo original.
2. Consultar equipo: Liverpool -> Generar DBC.
3. Consultar equipo: Belgrano -> Generar DBC.
4. Click en Actualización -> Intercambiar Jugadores.
5. Cargar archivos correspondientes a Liverpool y Belgrano.
6. Selecciona un jugador de Liverpool y dar click en >
7. Click en guardar.

### Versión PC-Fútbol

PCF6 - Apetura 98

### Hash/commit

eb12c081dddc6fb8d10e96ee6a014047ded710e1

**Comment by carky12** [comment]
Listo, el problema era que al intercambiar un jugador de una liga no jugable a un equipo de una liga jugable el campo PAIS DE NACIMIENTO se estaba intentando parsear como una nacionalidad, cuando en la BBDD del juego se guarda como un String directamente. En la siguiente versión que suba estará solucionado.
