### ISSUE TITLE
Generar DBC originales: Error al convertir a decimal: Valor de letra no conocido.

### ISSUE THREAD

**Issue by cressidagp** [carky12/EditorPCFutbol6#19]
### Descripción

Error al convertir a decimal: Valor de letra no conocido 3F - EQ960002.DBC
Error al convertir a decimal: Valor de letra no conocido DF - EQ969004.DBC

### Como reproducir

1. Menu Archivo -> Generar DBC originales -> Seleccionar EQ003003.pkf
2. Click en abrir.

### Versión PC-Fútbol

PCF5 - Apetura 97

### Hash/commit

eb12c081dddc6fb8d10e96ee6a014047ded710e1

**Comment by carky12** [comment]
¿El PCF5 - Apertura 97 tiene el archivo de equipos EQ003003.PKF?...
Por que ese es el nombre que tengo para el archivos de equipo en el PCF6 - Apertura 98.

Para el PCF5 - Apertura 97 tengo EQ003022.PKF...es correcto?

**Comment by cressidagp** [comment]
![pcf5](https://user-images.githubusercontent.com/63816325/126528872-d61f03bf-43ae-428d-8815-68b758878bc2.jpg)

Vealo usted mismo :D

**Comment by cressidagp** [comment]
Carky estoy recordando que salieron dos versiones del pcf5 Apertura 97. Una para Argentina (usa moneda peso argentino) y otra para Europa (creo usaba pesetas o euros). Esta última debe ser la que tienes tu.

**Comment by carky12** [comment]
Listo, me hice con esa versión y comprobé los errores en la carga. De todas formas en el manual va un apartado para solucionar este tipo de errores en la carga, por si se producen en tiempo de "ejecución" para no estar pendientes de cambiar el código, con añadir un valor al archivo map.txt será suficiente para seguir haciendo la carga del archivo sin que dé error.

De todas formas he probado a cagar todos los archivos de estas versiones:

![image](https://user-images.githubusercontent.com/57545449/126722320-c34df03a-3ea5-4d5d-bd9b-654d5b14d443.png)
