### ISSUE TITLE
tácticas personalizadas

### ISSUE THREAD

**Issue by cressidagp** [carky12/EditorPCFutbol6#2]
Importante ya que la mayoría de los equipos en pc fútbol 6 no usaban las tácticas predeterminadas.

Hay una opción en el viejo editor que te permite cargar el archivo con la táctica que guardamos en el juego.

**Comment by carky12** [comment]
Apuntado para la siguiente versión.

Gracias por el feedback!

**Comment by carky12** [comment]
Listo, en la siguiente versión ya estará disponible agregar una táctica personalizada

![image](https://user-images.githubusercontent.com/57545449/124888352-50693680-dfd6-11eb-8397-714d7c311333.png)
