### ISSUE TITLE
Error en la ultima version 25 Julio 2021

### ISSUE THREAD

**Issue by baillergeaux** [carky12/EditorPCFutbol6#20]
Hola **carky12**,

Acabo de probar la ultima version del editor y habiendo seguido los pasos habitales que ya te describi justo cuando le doy a boton de EDITAR a cualquier jugador, en este caso de la Juventus, me sale este error, Sabes por qué es? Gracias.

![25-07-2021 21-43-00](https://user-images.githubusercontent.com/87948476/126911179-1519281b-52ad-4b7a-803d-5bbb17e82ea9.jpg)

**Comment by carky12** [comment]
Hola, necesito saber como has generado el archivo DBC que estás intentando editar y para que versión del juego estás intentando editar.

**Comment by baillergeaux** [comment]
> Hola, necesito saber como has generado el archivo DBC que estás intentando editar y para que versión del juego estás intentando editar.

Hola,

Pues he:
- abierto el nuevo editor
- cargado equipos del PCF5.0, por lo tanto el archivo EQUIPOS.PKF
- luego, consultado equipos, concretamente poniendo Italia en pais, pinchando la Juventus y generado DBC de este mismo equipo.
- luego he ido a abrir DBC y lo he abierto buscandolo en la ruta "Editor PCF 6.0\EquiposDBC". Ahi estaba el nuevo DBC creado por el editor.
- lo he abierto, me he ido a plantilla y le he dado al boton de editar del jugador Zidane. Ahi es donde ha salido ese error.

**Comment by carky12** [comment]
He seguido los pasos tal y como indicas y no consigo reproducir el problema.

![image](https://user-images.githubusercontent.com/57545449/126911920-643fd6ff-8747-4181-9007-34905aa0aa7e.png)

A mi me edita perfectamente. Viendo el error que te da creo que tiene que ver con la versión de .NET instalada en tú PC. Voy a intentar quitar la dependencia a PowerPacks del proyecto y lo vuelvo a subir a ver si no te pasa.

Por curiosidad... ¿En qué versión de Windows estás ejecutando el editor?

**Comment by baillergeaux** [comment]
Si, sin saber mucho, a mi tambien me a parecido un problema de compatibilidad mas que del editor.

Utilizo Windows 7.

**Comment by carky12** [comment]
He subido una nueva versión añadiendo la librería que te da el error (Power Packs - es una librería de diseño de .NET). A modo informativo la versión de .NET que necesitas es la 4.0.0.

En cuanto puedas dime a ver si te funcionó.

**Comment by baillergeaux** [comment]
OK. Muchas gracias...!

**Comment by baillergeaux** [comment]
Sí! Ahora no da ese error.

Sigo editando y espero que cargue bien el juego 5.0.

Te seguiré contando.

**Comment by carky12** [comment]
Ok, cierro esta incidencia.

Cualquier otra cosa abres otra.

Muchas gracias por utilizar y probar el editor.
