### ISSUE TITLE
Rol de Mediapunta por la izquierda no permanece seleccionado

### ISSUE THREAD

**Issue by baillergeaux** [carky12/EditorPCFutbol6#21]
Hola carky12,

Al editar jugadores y darles el rol de Mediapunta por la izquierda, este rol no permanece seleccionado tras haber guardado los datos editados del jugador.

**Comment by carky12** [comment]
Corregido!

Gracias de nuevo por las pruebas!!!

PD: Confírmame que el juego te lee bien los archivos DBC y que puedes importar datos desde la web para crear equipos.
