### ISSUE TITLE
Crash al agregar un jugador a un dbc original.

### ISSUE THREAD

**Issue by cressidagp** [carky12/EditorPCFutbol6#22]
### Descripción

Al agregar un jugador a un equipo de liga extrangera se produce un crash.

NO ocurre si se crea un nuevo achivo DBC desde cero (ver archivo adjunto).
[EQ970305.zip](https://github.com/carky12/EditorPCFutbol6/files/6914749/EQ970305.zip)

### Como reproducir

1. Cargar archivo original.
2. Consultar equipo Liverpool.
3. Generar DBC.
4. Menu Equipos -> Abrir Archivo DBC -> EQ970305.DBC.
5. Plantilla -> Nuevo jugador.
6. Guardar.
7. Copiar archivo a la carpeta EQ003003.
8. Ejectuar - > Liga Manager.

### Versión PC-Fútbol

PCF6 - Apetura 98

### Hash/commit

50ebfffeba7c66268c4c9b830e1c71277e79b012

**Comment by carky12** [comment]
Lo he solucionado junto con un error que tenía que ver con esto, y sólo se daba al editar los DBC originales del juego. Tanto al añadir algún jugador, como al cambiar algún texto relacionado con algún jugador daba un crash.
