### ISSUE TITLE
DBC Leyendas bug cosmetico.

### ISSUE THREAD

**Issue by cressidagp** [carky12/EditorPCFutbol6#23]
### Descripción

Por ejemplo si buscamos a Michael Laudrup vemos que nos dice el nombre del equipo japones en el que esta jugando.

![leyenda original](https://user-images.githubusercontent.com/63816325/127814038-621d6464-d8df-4afd-8704-232de026082a.jpg)

Pero si agregamos una leyenda nueva por ejemplo Cantona, en lugar de ver el nombre del equipo nos aparece una x.

![leyenda agregada](https://user-images.githubusercontent.com/63816325/127814234-fd80ce49-6f84-4275-ad84-a37a54b846ca.jpg)

### Como reproducir

1. Agregar un jugador al dbc de leyendas.
2. Buscarla en el secretario tecnico (seleccionando rol y media para asegurar el exito de la busqueda).

### Versión PC-Fútbol

PCF6 - Apetura 98

### Hash/commit

50ebfffeba7c66268c4c9b830e1c71277e79b012

**Comment by carky12** [comment]
Para el equipo de estrellas, el equipo de procedencia del jugador lo coge del dato que hay en el Club de Debbut

![image](https://user-images.githubusercontent.com/57545449/130705466-08f6be0a-9edd-453b-a652-8e814f1a29f5.png)

![image](https://user-images.githubusercontent.com/57545449/130705476-4ec1c916-51ff-476b-9ace-e864c633321a.png)

**Comment by cressidagp** [comment]
Enterado Carky! Gracias
