### ISSUE TITLE
La opción INTERCAMBIAR JUGADORES parece no conservar los punteros originales

### ISSUE THREAD

**Issue by baillergeaux** [carky12/EditorPCFutbol6#24]
Al utilizar la opción INTERCAMBIAR JUGADORES, cuando un jugador se mueve a otro equipo parece que no conserva su propio puntero.

Lo digo porque en el 5.0 he movido a Ronaldo Nazario del Barcelona al Inter de Milán y luego he simulado un partido amistoso entre los dos. Todo funcionaba bien y el intercambio se ha hecho correctamente pero Ronaldo en el Inter ya no aparecía con su foto original sino con ninguna y en el simulador. A su vez, con el Ronaldo que es original del juego ocurre una cosa muy curiosa en el simulador del 5.0, él es el unico jugador que celebra los golos de una forma única la cual es haciendo el avión con los brazos que hacía Ronaldo en la vida real antiguamente cuando jugaba.  El caso es que el Ronaldo movido al Inter ya no hace eso y celebra los goles como cualquier otro jugador por lo que me imagino que no tiene mismo puntero de jugador sino que simplemente es una copia idéntica con otro puntero.

Sería posible que hubiera la opción de que los jugadores intercambiados con esa opción del editor conservaran su puntero también en el nuevo equipo? Sería tal y como hace el juego cuando los jugaores son traspasados.

**Comment by carky12** [comment]
Hola, he solucionado el problema. Al intercambiar jugadores entre dos equipos no pasaba...sólo pasaba cuando se traspasaba un jugador del equipo de la derecha al de la izquierda o viceversa.

Ya está solucionado, y en cada traspaso que se haga desde la pantalla de intercambio de jugadores se respetan los punteros originales del juego.

PD: Yo vi en directo el gol de Ronaldo Nazario en Santiago de Compostela!!!
Gracias por reportarme el error y usar el editor.

**Comment by baillergeaux** [comment]
Hola @carky12 , genial, muchas gracias. Ya funciona de maravilla.

Por cierto, yo también vi el gol de Ronaldo contra en Compostela en directo, por la tele por supuesto, estaba en casa viendo ese partido un poco sin prestarle mucha atención porque tampoco parecía que iba a ser un partido muy trascendete, cuando de repente vi esa jugada desde su inicio hasta el final, me quede totalmente alucinado...!
