### ISSUE TITLE
crear nuevos punteros en ligas no jugables

### ISSUE THREAD

**Issue by cressidagp** [carky12/EditorPCFutbol6#3]
Esto ya es mas utópico, pero como dicen: "...de los grandes sueños surgen los grandes logros..."

Estaría bueno poder crear punteros para agregar mas equipos en ligas no jugables ya que hay muchas que tienen apenas 2 o 3 equipos. 

Algunos usuarios del foro encontraron una forma "hardcoded" de hacer esto. Estaría bueno una opción que sea accesible al usuario común.

**Comment by carky12** [comment]
Hola cressidagp,

esto ya se puede hacer, te explico el procedimiento, por ejemplo para crear un equipo para la liga Brasileña:

1. Creas un DBC desde el editor.
2. Seleccionas Brasil como país del equipo.
2. No seleccionas ningún equipo para que te guarde el archivo como EQ970000.DBC
3. Buscas un puntero que no sea de ninguno de los equipos que hay en el juego (el que tú quieras) y se lo pones al archivo.
4. Con esto es suficiente, cuando entres al juego ya te aparecerá el equipo en la liga

PD: Hay una lista de punteros que puedes utilizar, en la que están todos los punteros de PCFútbol. Incluso de equipos que no hay en el juego. Lo tengo dentro de la carpeta Manuales. Te dejo el [enlace](https://github.com/carky12/EditorPCFutbol6/blob/master/Manuales/Punteros%20Equipos.pdf).

Espero que te ayude.
Un saludo

**Comment by cressidagp** [comment]
Gracias Carky, había visto el manual pero me daba la sensación de que esos punteros de equipos ausentes no aparecían en la versión Argentina y por eso los chicos del foro usaban habían buscado la forma de agregar nuevos punteros.

**Comment by cressidagp** [comment]
Hola Carky, esa lista de punteros que tienes allí es de pcfutbol 2000, se me hacia raro que hubiera punteros disponibles en pcftubol6. 

Saludos!

**Comment by carky12** [comment]
Hola,

si es una lista de punteros de pcf2001. Es la lista que se utiliza para crear equipos en ligas extranjeras (por ejemplo Brasil). Lo único que tienes que hacer es crear el DBC con el país correspondiente a la liga que quieres crear, y usar un puntero de esa lista que no corresponda a ningún equipo de PCF6 y listo.

Un saludo.

**Comment by cressidagp** [comment]
![cosme fulanito](https://user-images.githubusercontent.com/63816325/105500360-912bf800-5ca1-11eb-9a69-0807f99a7aa5.png)

Hola Carky, he intentado hacer como dices y quise poner el puntero 5757, pero por algún motivo no me deja tipear el nombre del puntero, solo me permite seleccionar de una lista... y por ejemplo 5757 no esta...

**Comment by carky12** [comment]
Hola,

tal y como explico en el manual ese campo "PUNTERO DECIMAL" no se puede escribir, es para facilitar la generación de archivos DBC. Me explico:

Si quieres generar un archivo DBC para el Real Madrid, con el editor haces todo (pones táctica, creas jugadores, etc...) y después seleccionas de la lista de equipos el Real Madrid para que al darle al botón guardar te genere el archivo EQ970004.DBC.

Pero si por el contrario no seleccionas ningún equipo y le das a guardar el editor te guarda un archivo EQ970000.DBC, es decir sin ningún puntero asociado. Lo que tienes que hacer es, una vez generado este fichero, cambiarle el nombre y ponerle eq975757.DBC y listo.

Ya me contarás a ver si lo consigues.
Un saludo.

**Comment by cressidagp** [comment]
Hola Carky, ahora si entendí! Probé de hacer todo como me dijiste. Pero estando ya dentro del juego si hago click en la banderita de Brasil aparece el cartel: la aplicación no puede continuar y se produce un crash. Me sucedió con los dos punteros que probé: 0111 y 9061.

El crash se produce tanto al elegir equipo desde: Partido Amistoso así como también si juego en la liga manager y quiero ver los equipos de Brasil.

**Comment by carky12** [comment]
Hola,

una imagen vale mas que mil palabras...te he subido un video a YouTube para que veas como se hace. Si te da algún error de que la aplicación no puede continuar será por que el archivo DBC generado no está bien.

https://youtu.be/16s1iH7Y1Fg

Un saludo.

**Comment by cressidagp** [comment]
Hola Carky muchas gracias por toda tu ayuda. Lamentablemente hice todo como lo has hecho tu y sigue crasheando. Lo único diferente es que tu usas la versión española y yo la Apertura 98. Debe ser que ambas son diferentes.

Saludos

**Comment by carky12** [comment]
Hola,

pues tienes razón, he probado lo mismo en la versión Argentina y no funciona! A ver si puedes averiguar algo, por que yo no tengo tiempo para averiguar y programar.

Si yo averiguo algo te lo haré saber.

Gracias.
Un saludo.

**Comment by cressidagp** [comment]
Hola Carky!

Te comento por las dudas que encontré algo en mi antigua computadora. Pero no estoy seguro que vaya a servir. Tengo un PCFtubol6 de argentina ( aparentemente actualizado en 2015) y tiene muchísimos equipos extras en ligas no jugables. Intente probar de abrir uno de los archivos DBC con tu editor para salta el siguiente error:

Se han producido errores en la carga del fichero DBC. Error al convertir a decimal: valor de letra no conocido D4

**Comment by carky12** [comment]
Hola

esto que me comentas es perfecto. Envíame alguno de los archivos DBC que corresponden a algún equipo nuevo de alguna liga extranjera. Si no lo das localizado, envíame toda la carpeta de archivos DBC (súbela al drive y envíame enlace). Analizo el patrón y cambio el editor para que pueda tratar esos ficheros.

PD: Sólo para asegurar que estamos con la misma versión...estamos hablando del PCF 6.0 Apertura 98 (tamaño del MANAGARG.EXE = 2397 KB)

Gracias!

**Comment by cressidagp** [comment]
Hola Carky. Efectivamente es la misma versión PCF 6.0 Apertura 98 (2397KB). Un dato curioso es que arreglaron el problema de la bandera de Macedonia y Bielorusia. Además le actualizaron el nombre a yugoslavia. Y transformaron a Azerbaiyán en Resto del Mundo (donde pusieron equipos de Mexico y USA. No lograron arreglar el problema de las convocatorias internacionales ni tampoco la ausencia de voces de los empleados.

Estoy subiendo todo a drive. Saludos!!!

**Comment by carky12** [comment]
Hola, esto me va a ayudar mucho.
En cuanto pueda miro los DBC y analizo los ficheros a ver que tal. No te prometo nada que ando a tope de curro.
Ya llevo anotadas unas cuantas cosas para mejorar en el EDITOR, si tú sigues encontrando cosas dime que por lo menos lo vamos puliendo entre todos.

Gracias de nuevo.
Un saludo.

**Comment by carky12** [comment]
Hola,

lo he mirado por encima. Te cuento cual es el problema. Con mi editor puedes abrir los archivos DBC del juego que me pasas con la opción que pone "ABRIR ARCHIVO DBC (FORMATO 5.0). Una vez abierto puedes hacer la edición de forma normal. Al guardarlo tienes que tener marcado la opción que pone "USAR FORMATO 5.0 PARA GUARDAR EL ARCHIVO". Con esto vas a poder editar esos ficheros.

![image](https://user-images.githubusercontent.com/57545449/105824733-0d368080-5fbf-11eb-90b2-7b8479489cea.png)

Aún hay un problema a mayores, que solucionaré en futuras versiones. Al guardar desde mi editor, el tamaño de los ficheros es de 50 KB, pero para esta versión Argentina tienen que ser de 7KB (6161 Bytes). Lo que puedes hacer para que te valgan es borrar los bytes de más entre el 6161 y el final del archivo generado con mi editor (son todo "00000000...." así que no hay problema en eliminar esos bytes).

Yo he probado a hacer esto y pude editar y crear equipos nuevos para otras ligas. Tendré que pulir el editor para adecuar el guardado para las diferentes versiones de PCF 6.

Un saludo.

**Comment by cressidagp** [comment]
Hola Carky, me alegro que te haya servido lo que te mande. Ojala en un futuro tengamos editor para todos los PC-Fútbol 6. 

Un abrazo!

**Comment by carky12** [comment]
Hola, si que me sirvió. Hasta dentro de bastantes meses no tendré tiempo para dedicarle a este proyecto. Por si quieres editar y crear archivos para esa versión puedes hacer lo que te dije, generar los DBC con el EDITOR y quitar los bytes sobrantes desde la posición 6161.

Un saludo.

**Comment by carky12** [comment]
Hola, ya estoy disponible para meterme de lleno con los cambios en el editor.

Tengo bastantes cosas apuntadas, y con la ayuda de lo que me has pasado tú espero mejorarlo bastante.

Un saludo.

**Comment by cressidagp** [comment]
Hola Carky! Que alegría!! ¿Cómo estás? 

Ese editor va a quedar épico!!! Yo aquí a disposición para testear y reportar. 

Un abrazo! Larga vida al PC-Futbol \o/

**Comment by carky12** [comment]
Hola, he planteado una pregunta en el foro sobre el tema de crear equipos en las versiones PCF Apertura 98, PC Premier 6.0 y PC Calcio 6.0.

https://www.pcfutbolmania.com/thread-12188.html

A ver si alguien responde, ya que no doy con el problema. En las versiones mencionadas sólo puedo crear equipos si nombro los archivos con punteros de equipos que ya están en el juego. Para las demás versiones puedo crear equipos utilizando punteros que no existen en el juego con lo que es bastante suculento ya que puedes crear equipos sin "destruir" los que ya tienes en el juego.

Por ahora dejo esto aparcado hasta que alguien me diga como hacer, por que ya estoy aburrido de investigar.

**Comment by cressidagp** [comment]
offtopic: algo para reflexionar... 

Si las versiones Apertura, Premier y Calcio están tan llenas de bugs no seria conveniente trabajar directamente en un editor de la versión española y agregar alguna funcionalidad que permita intercambiar/reemplazar Liga española por Liga Premier por ejemplo, Nose quizás me fume un porro y estoy delirando mucho...

**Comment by carky12** [comment]
Nada, no te preocupes, no estoy perdiendo tiempo en implementara nada especial para esas versiones. Lo mejor es seguir como hasta ahora. Si nadie da con la clave de crear nuevos equipos en ligas no jugables sin utilizar punteros de equipos del juego pues no se crean equipos y listo, pero se pueden actualizar los que hay en el juego sin problema.

Esto es interesante por si quieres jugar con un equipo inglés por ejemplo (o argentino o italiano), que en mi caso me cunde.

Y si no siempre queda la opción de hacer algo como lo que hicieron en el juego editado que me pasaste...usar equipos de mierda (tipo Finlandia o Islandia) para crear nuevos equipos en otras ligas, o incluso crear un RESTO DEL MUNDO.
