### ISSUE TITLE
soporte obtener datos de la web bdfa

### ISSUE THREAD

**Issue by cressidagp** [carky12/EditorPCFutbol6#4]
Hola!

Estuve probando el tema de importar datos desde la web (mas allá de que no soy muy fanático del futbol actual, prefiero usar jugadores vintage) y note que las web disponibles no tienen equipos de segunda división argentina.

Les propongo una web que puede dar solución a dicho problema:

https://www.bdfa.com.ar/argentina-b-nacional.html

Saludos

**Comment by carky12** [comment]
Listo, el editor ya soporta actualización desde la página BDFA.

En la siguiente publicación esta funcionalidad ya estará activa!

**Comment by carky12** [comment]
![image](https://user-images.githubusercontent.com/57545449/124837321-e83e3480-df84-11eb-9011-c0d941102918.png)

**Comment by cressidagp** [comment]
Excelente!
