### ISSUE TITLE
juveniles: el editor solo permite 35 jugadores

### ISSUE THREAD

**Issue by cressidagp** [carky12/EditorPCFutbol6#5]
Hola Carky, he obtenido ese error al intentar crear un fichero para los juveniles de PC6 Apertura 98.

Según han comentado en el foro se trata de un puntero especial por lo que no debería tener ese limite ( otro developer menciono el número 300 pero no estoy que el numero este verificado ).

**Comment by carky12** [comment]
Estoy implementando funcionalidades para leer y escribir archivos DBC de juveniles. En dichos archivos DBC el límite de jugadores será de 150.

**Comment by carky12** [comment]
Listo, he implementado un menú para gestionar los archivos de juveniles.

![image](https://user-images.githubusercontent.com/57545449/124940610-6db7f800-e00a-11eb-9b73-d6f9be7859ad.png)

![image](https://user-images.githubusercontent.com/57545449/124940637-714b7f00-e00a-11eb-9099-5cbab05609c7.png)

Y el resultado en el juego:

![image](https://user-images.githubusercontent.com/57545449/124940675-77d9f680-e00a-11eb-9563-6deb10cf9810.png)

El límite para estos equipos es de 150 jugadores.

**Comment by cressidagp** [comment]
Brillante Carky!!!
