### ISSUE TITLE
Libres: el editor solo permite 35 jugadores.

### ISSUE THREAD

**Issue by cressidagp** [carky12/EditorPCFutbol6#7]
Ídem anteriores. 

Aunque mas allá de lo que diga el otro desarrollador de la comunidad pcfutbolmania, no he logrado hacer que dichos jugadores aparezcan en la búsqueda del secretario técnico. 

Posible número de puntero incorrecto.

**Comment by carky12** [comment]
El puntero correcto es 9950, es decir el fichero es EQ979950.DBC. Pero no consigo que me salgan en las búsquedas del secretario. No le voy a dedicar tiempo a esto, lo postearé y si alguien responde lo implemento pero no merece la pena perder tiempo en investigar esto.

PD: He probado con el juego que me habías pasado que ya venía "toqueteado/actualizado" y he visto que también tiene el fichero DBC correspondiente a los jugadores libres, pero no hay manera de que aparezcan en el secretario.

**Comment by cressidagp** [comment]
Bueno en ese caso ya estaría listo? O acaso trabajáis en alguna cosilla sorpresa? :D

**Comment by carky12** [comment]
Estoy haciendo cosas que pidieron usuarios del foro y que además creo que pueden ser muy útiles.

PD: Cuando pones "trabajáis" es mas bien "trabajo" que en esto estoy yo solo ajajaja.....y con tú única ayuda con tester!

**Comment by cressidagp** [comment]
Pues yo lamento no ser mas útil. Estoy aprendiendo C++ en forma autodidacta desde el inicio de la pandemia pero aun estoy muy verde. Aunque mas que tester me siento "Quality Assurance".

**Comment by cressidagp** [comment]
¿Qué tienen en común PCF5, Apetura 97, PCF6, Calcio 6, Premier 6, Apetura 98?

Pues el curioso caso de Stanley Collymore. 

![Sin título](https://user-images.githubusercontent.com/63816325/126243462-58d8928e-1415-41d3-8a42-37c4564912a6.jpg)

Este muchacho supo ser miembro del grupete de los "Spice Boys" de Liverpool por aquellos días. Pero se fue desinflando puesto a que tenia muchos problemas en su vida privada si mal no recuerdo. Por algún motivo aparece en todas las dbc de "supuestos libres" y con media de 88. 

Pero la cosa no termina ahí... puesto que Stanley Collymore también aparece en el Aston Villa, solo que allí su media es 83.

¿Como permaneció esto durante tantas versiones? Curiosidades que me gustara preguntarle a los creadores del juego.
