### ISSUE TITLE
Menú contextual con opciones para jugadores

### ISSUE THREAD

**Issue by carky12** [carky12/EditorPCFutbol6#9]
Se implementa un menú contextual para facilitar el acceso a operaciones con jugadores. Se implementa además la operación de copiar jugador. Con esta opción se pueden copiar jugadores vaciando el puntero para el correcto guardado del jugador.

![image](https://user-images.githubusercontent.com/57545449/125101160-34e75400-e0da-11eb-90dd-855b066b8195.png)

**Comment by cressidagp** [comment]
Sin duda esto sera muy útil.
